#!/usr/bin/env python3
"""Collect per-library prompts into a single okw-complete.md.

Run from any directory — paths are resolved relative to this script.
All library prompts under ``D:/work/okw/robotframework/`` are discovered
automatically via the SOURCES list below.

Usage::

    python prompts/build-prompt.py
"""

from __future__ import annotations

import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OKW_ROOT = SCRIPT_DIR.parent.parent  # D:/work/okw

# (section title, path relative to OKW_ROOT)
SOURCES: list[tuple[str, str]] = [
    (
        "OKW GUI + SSH Keywords (okw4robot)",
        "robotframework/robotframework-okw4robot/prompts/okw-testgenerator.md",
    ),
    (
        "OKW YAML Locator Generator (okw4robot)",
        "robotframework/robotframework-okw4robot/prompts/okw-locator-generator.md",
    ),
    (
        "OKW REST API Keywords (okw-api-rest)",
        "robotframework/robotframework-okw-api-rest/prompts/okw-rest-test-generator.md",
    ),
    (
        "OKW Environment Provisioning (okw-env / okw-env-docker)",
        "robotframework/robotframework-okw-env/prompts/okw-env-generator.md",
    ),
]

OUTPUT = SCRIPT_DIR / "okw-complete.md"


def build() -> None:
    parts: list[str] = []

    parts.append("# OKW Complete Prompt — All Keywords, All Libraries\n")
    parts.append(
        "> Auto-generated by `build-prompt.py` — do not edit manually.\n"
        f"> Generated: {datetime.date.today().isoformat()}\n"
    )
    parts.append(
        "This prompt contains **all OKW keywords** across all libraries.\n"
        "Give this file to any AI to enable it to generate runnable OKW tests,\n"
        "YAML files, and project-specific widget classes.\n"
    )
    parts.append(
        "## Included Libraries\n\n"
        "| Library | Install | Purpose |\n"
        "|---|---|---|\n"
        "| `robotframework-okw4robot` | `pip install robotframework-okw4robot` | Core GUI + SSH keywords |\n"
        "| `robotframework-okw-api-rest` | `pip install robotframework-okw-api-rest` | REST API keywords |\n"
        "| `robotframework-okw-env-docker` | `pip install robotframework-okw-env-docker` | Docker environment provisioning |\n"
        "| `robotframework-okw-web-selenium` | `pip install robotframework-okw-web-selenium` | Selenium WebDriver plugin |\n"
        "| `robotframework-okw-java-remoteswing` | `pip install robotframework-okw-java-remoteswing` | Java Swing plugin |\n"
    )

    missing: list[str] = []
    for title, rel_path in SOURCES:
        src = OKW_ROOT / rel_path
        if not src.exists():
            missing.append(str(src))
            continue

        content = src.read_text(encoding="utf-8")
        # Strip leading H1 from individual prompts (we provide our own structure)
        lines = content.split("\n")
        if lines and lines[0].startswith("# "):
            lines = lines[1:]
        content = "\n".join(lines).strip()

        parts.append(f"---\n\n## {title}\n\n{content}\n")

    if missing:
        print(f"WARNING: {len(missing)} prompt file(s) not found:")
        for m in missing:
            print(f"  - {m}")

    OUTPUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"OK: {OUTPUT}  ({len(SOURCES) - len(missing)}/{len(SOURCES)} sources)")


if __name__ == "__main__":
    build()
